package irysc.gachesefid.Models;

public enum NewAlert {

    INIT_FORM_NOT_MARKED, INIT_FORM_MARKED_NOT_CLASS_ASSIGN, NEW_TICKETS,
    OPEN_TICKETS_WAIT_FOR_ADMIN, NEW_CERTIFICATE_REQUESTS,
    OPEN_CERTIFICATE_REQUESTS_WAIT_FOR_ADMIN,
    OPEN_INTERVIEW_REQUESTS_WAIT_FOR_ADMIN,
    OPEN_INIT_FORM_REQUESTS_WAIT_FOR_ADMIN,
    NEW_INTERVIEW_REQUEST, NOT_RESULT_INTERVIEW_REQUEST, NOT_TEACHER_ASSIGNED_INTERVIEW_REQUEST;

    public String getName() {
        return name().toLowerCase();
    }
}
